[package]
name = "krisp"
version = "0.1.0"
authors = ["Benjamin Kulas <nazekthetweaker@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
lazy_static = "1.3.0"
rustyline = "3.0.0"
bacon_rajan_cc = "0.2.3"
dirs = "1.0"
downcast-rs = "1.0.4"
